annotation: S2
checkpoint: ''
dataset: drugbank
ddi_dict_path: upload/model/configs/DDI_dict_action_roberta.json
deepspeed: false
drug_name_only: false
drug_only_max_length: 48
epsilon: 1.0e-08
eval: false
eval_batch_size: 128
filemode: w
fp16: false
gpu_num: 1
gpuid: '5'
gradient_accumulation_steps: 1
log_step: 10
lr: 1.0e-05
lr_scheduler_type: constant
max_length: 256
max_train_steps: 0
model_type: roberta_cls
multi_gpu: false
not_random: false
num_train_epochs: 20
patience: 5
per_gpu_train_batch_size: 32
pretrained_model_path: upload/model/pretrained_models/roberta-base
resume: false
s_num: S2
seed: 123
shot_num: 5
test: true
use_few_shot: false
use_gpu: true
use_id: false
use_zero_shot: true
vocab_size: 50257
weight_decay: 1.0e-06
